on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip | tee pip_install.log
          pip install -r requirements.txt | tee requirements_install.log

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | tee flake8_lint.log
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics | tee flake8_lint_full.log

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip | tee pip_install.log
          pip install -r requirements.txt | tee requirements_install.log

      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Run the Python script
        run: |
          python main.py | tee main_script.log