name: Node.js Package using pip

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install Python dependencies
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Run code
      run: |
        python main.py  # Run the Python script (main.py)
